### ISSUE TITLE
Compilling for linux

### ISSUE THREAD

**Issue by vSongBook** [utelle/wxsqlite3#80] opened 2019-10-06 12:20 UTC
Hi there am lost in trying to compile for linux those I was able to compile for windows. Your instructions are very scanty when it come to linux

I tried this:
```
mkdir build-gtk
cd build-gtk
../configure --disable-shared
make
```
>  CXXLD    samples/minimal
> /usr/bin/ld: ./.libs/libwxcode_gtk3u_wxsqlite3-3.1.a(sqlite3secure.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
> /usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:672: samples/minimal] Error 1
> 

maybe its a configure flag am not sure. Am trying to read what other devs have said elsewhere

**Comment by utelle** [comment] 2019-10-06 14:26
Since most of my development takes place under Windows my knowledge of Linux systems is limited unfortunately. However, I was able to reproduce the problem. It seems to be a side effect of the configure option `--disable-shared`.

Please add the following line in `Makefile.am` (after the definition of `AM_CFLAGS` before the definition of `LDADD` ):
```
AM_LDFLAGS = -pthread -ldl -lm
```
Thereafter execute `configure` again. This should solve the issue.

**Comment by utelle** [comment] 2019-10-15 03:39
I integrated the mentioned modification into the latest version(s) of wxSQLite3.

This should solve your issue. Therefore I'm closing it. Reopen if necessary.

**Closed by utelle** 2019-10-15 03:39 UTC
