### ISSUE TITLE
Convertion non-encrypted database to SQLCipher/ChaCha20 format

### ISSUE THREAD

**Issue by lagurus** [utelle/wxsqlite3#27] opened 2018-04-11 10:38 UTC
Hi,

I am not able to convert existing non-encrypted DB into SQLCipher/ChaCha20. It lead
to crash in function CodecCopy(Codec* codec, Codec* other). It seems that 
codec->m_readCipherType=0.

Following command typed into sqlite3shell.exe lead to crash.

sqlite3shell.exe test2.db

sqlite> SELECT wxsqlite3_config("cipher", "sqlcipher" );
sqlite> pragma rekey='pass';

test2.db is unencrypted database with one table.
It seems that in this case is needed to use sqlite3RunVacuumForRekey which later lead to crash.

No problem with CODEC_TYPE_AES128 and CODEC_TYPE_AES256.
Also is possible to create empty encrypted database with every codec.

Thanks

**Comment by utelle** [comment] 2018-04-11 14:46
Unfortunately, I have to confirm that this is a bug that slipped through.

For plain, not encrypted databases no read cipher is set. That is, it has to be checked whether a cipher type is associated at all, before using it.

While verifying this bug I detected another glitch. I'll try to fix the issue within the next few days.

**Comment by utelle** [comment] 2018-04-11 20:12
Encrypting a plain database should now work as expected.

BTW, if you want to create a database that can be processed by an application that is based on the original SQLCipher, special action has to be taken. 

First, it is required to set the `legacy` parameter for the `sqlcipher` cipher to **1**, since the original SQLCipher encrypts the complete database header. 

Second, you have to take care of adjusting the database page size. The default page size of plain SQLite databases is 4096, while the default page size of SQLCipher databases is 1024. Unfortunately, the function `sqlite3_rekey`is not able to change the page size of the resulting encrypted database. That is, if the plain database has a page size of 4096, then the encrypted database will also have a page size of 4096. So, you either have to change the page size of the plain database before rekeying or you have to use `PRAGMA cipher_page_size=4096` in the SQLCipher application (if that is possible).

**Comment by utelle** [comment] 2018-04-12 08:51
Fixed in release [wxSQLite3 4.0.1](https://github.com/utelle/wxsqlite3/releases/tag/v4.0.0).

**Closed by utelle** 2018-04-12 08:51 UTC
Labels: bug

**Comment by devbean** [comment] 2018-09-11 14:06
Hi, I read about the above answers and tried to convert plain database file to SQLCipher format using
```c
wxsqlite3_config_cipher(d->access, "sqlcipher", "legacy", 1);
wxsqlite3_config_cipher(d->access, "sqlcipher", "legacy_page_size", 4096);
...
const int result = sqlite3_rekey(d->access, 'pass', 4);
```
with wxSQLite3 4.0.4 but the result is always `SQLITE_CORRUPT`. Even try to change `legacy_page_size` to 1024 the result is always the same. How should I solve this problem?

**Comment by utelle** [comment] 2018-09-11 20:57
When do you get the error message `SQLITE_CORRUPT`? Did you try to open the encrypted database in an application with SQLCipher support or in your own application?

At least one missing piece in your code sample is the following call to `wxsqlite3_config`, which takes care of setting the cipher which should be used - in your case SQLCipher. If you compiled the wxSQLite3 encryption extension with the default settings then the default cipher is ChaCha20. Therefore you have to explicitly set the cipher.
```
wxsqlite3_config(db, "cipher", CODEC_TYPE_SQLCIPHER);
```
The second point is that legacy SQLCipher always uses page size 1024, unless the application chooses to overwrite this using a special SQLCipher pragma. That is, you need to know which exact SQLCipher settings your target application uses.

The third observation is that you pass your encryption password enclosed in single quotes (which denote usually single characters, in your case the compiler will transform it to an `int` - didn't you get a compiler warning?) instead of double quotes (which denote zero terminated character strings). That is, if your target application uses a password string the used password is most likely different from that in your sample code.

**Comment by devbean** [comment] 2018-09-12 01:01
I'm sorry for my bad code. I mistook quotes for I didn't copy code directly (JS code recently). Here is what I code (pseudo-code):
```
if (sqlite3_open_v2(db, &d->access, openMode, nullptr) == SQLITE_OK) {
    wxsqlite3_config(d->access, "cipher", CODEC_TYPE_SQLCIPHER);
    wxsqlite3_config_cipher(d->access, "sqlcipher", "legacy", 1);
    wxsqlite3_config_cipher(d->access, "sqlcipher", "legacy_page_size", 1024);
    const int result = sqlite3_rekey(d->access, "pass", 4);
    if (SQLITE_OK != result) {
        return false;
    }
}
```
Here `sqlite3_open_v2` successfully then `result` got `SQLITE_CORRUPT`. I did even not reach page size, `sqlite3_rekey` was incorrect so the original database file was not encrypted.

**Comment by utelle** [comment] 2018-09-12 09:47
I did some testing in the meantime. I can confirm that `sqlite3_rekey` returns an error under the given circumstances. The reason seems to be that the default page size (of the plain database) is 4096 bytes, while the requested page size is 1024. All non-legacy test cases using the default page size worked flawlessly.

I have to further investigate whether I can find a solution. However, chances are that there is no easy solution, because I found the following comment in the SQLite source:
```/* A VACUUM cannot change the pagesize of an encrypted database. */```
Due to the fact that SQLCipher requires reserved bytes per page, it is necessary to use a (slightly modfied) version of VACUUM to rekey (encrypt) the database.

A workaround is to change the page size of the plain database first. To do this you can issue the following SQL commands:
```
PRAGMA page_size=1024;
VACUUM;
```
Thereafter rekeying in legacy SQLCipher mode works.

**Comment by devbean** [comment] 2018-09-13 01:33
Thank you for your wonderful work. And yes I found out the all non-legacy mode worked prefectly.

**Comment by utelle** [comment] 2018-09-13 07:47
As far as I can tell it is not possible to change the database page size during a rekey operation. Most likely I will have to document this deficiency. In fact, the function `sqlite3_rekey` is meant to change the key/password only, not the database page size nor the number of reserved bytes per database page.

If only the key/password is changed function `sqlite3_rekey` operates in-place, that is, no temporary database file is created. However, if the number of reserved bytes changes (which is the case for encrypting a plain database with one of the new cipher schemes, ChaCha20 or SQLCipher) a slightly adjusted version of the VACUUM command has to be used, and a temporary copy of the database will be created, which is then copied back to the original database file.

Due to the deficiencies of the function `sqlite3_rekey` SQLCipher chose a different approach to encrypt a plain database or to decrypt an encrypted database: the SQL function `sqlcipher_export` is used to encrypt/decrypt a database. In this case a encrypted/decrypted copy of the database is created, but the original database is not modfied.

Maybe I should add such a function to wxSQLite3, too, to overcome the deficiencies of `sqlite3_rekey`.

BTW, in my tests I got a `SQLITE_CORRUPT` result also if I explicitly set the parameter `legacy_page_size` to 4096 in legacy SQLCipher mode. The reason is that the number of reserved bytes is not reported properly to the encryption function. At the moment I have no idea why that is so, because this happens deep in the original SQLite code. Of course, I will try to fix this, if possible, but it may take quite some time.

The best approach to work with encrypted databases is to directly create an encrypted database instead of starting with a plain database and to encrypt it later. If you create a new empty database, you can set page size and cipher as required and then use `sqlite3_key` to activate the encryption. This has to be the very first action after opening the database with `sqlite3_open`.

**Comment by utelle** [comment] 2018-09-21 15:58
[wxSQLite3 4.1.0](https://github.com/utelle/wxsqlite3/releases/tag/v4.1.0) (commit d19bfad7c9bd4bd2773655421c60453510bbf75b) includes adjustments to the encryption extension, so that `sqlite3_rekey` now works for legacy ciphers as long as the legacy page size matches the page size of the source database.

`sqlite3_rekey` will now fail with `SQLITE_ERROR` if the page sizes of the source and target database do not match. This is a limitation of SQLite itself.
