### ISSUE TITLE
includedir cannot be controlled properly

### ISSUE THREAD

**Issue by hasufell** [utelle/wxsqlite3#3] opened 2016-05-14 13:06 UTC
This is because `bakefile` (the build system) is a horrible mess. And makes random assumptions about what I want.

But we need that because otherwise the pkgconfig file line https://github.com/utelle/wxsqlite3/blob/master/wxsqlite3.pc.in#L5 doesn't work anyway.

E.g. in that [codeblock](https://github.com/utelle/wxsqlite3/blob/master/Makefile.in#L265) it does
```Makefile
@COND_SHARED_0@install_wxsqlite3_lib_headers: 
@COND_SHARED_0@	$(INSTALL_DIR) $(DESTDIR)$(prefix)
@COND_SHARED_0@	for f in $(WXSQLITE3_LIB_HEADERS); do \
@COND_SHARED_0@	if test ! -d $(DESTDIR)$(prefix)/`dirname $$f` ; then \
@COND_SHARED_0@	$(INSTALL_DIR) $(DESTDIR)$(prefix)/`dirname $$f`; \
@COND_SHARED_0@	fi; \
@COND_SHARED_0@	$(INSTALL_DATA) $(srcdir)/$$f $(DESTDIR)$(prefix)/$$f; \
@COND_SHARED_0@	done
```

Which means the source dir path gets mangled into the destination path because of `dirname`. bakefile supports the `$(INCLUDEDIR)` setting though, which can be used instead of `$(PREFIX)`. However, you can still not control the directory properly because `include/wx` is _always_ hardcoded because of that stupid `dirname` call above which is generated code.

So I just made a symlink `wx` to fix that. It also seems that the bakefile version used here is not maintained anymore, so I'm not going to try to fix that.

Here's the patch
```diff
diff --git a/build/wxsqlite3.bkl b/build/wxsqlite3.bkl
index 7d0f380..92d4b94 100644
--- a/build/wxsqlite3.bkl
+++ b/build/wxsqlite3.bkl
@@ -22,10 +22,10 @@
 
   <!-- COMP_HDR lists the component's headers with path relative to ../include -->
   <set var="COMP_HDR">
-    include/wx/wxsqlite3def.h
-	include/wx/wxsqlite3.h
-	include/wx/wxsqlite3dyn.h
-	include/wx/wxsqlite3opt.h
+    wx/wxsqlite3def.h
+	wx/wxsqlite3.h
+	wx/wxsqlite3dyn.h
+	wx/wxsqlite3opt.h
   </set>
   
   <set var="USE_DYNAMIC_SQLITE3_LOAD_DEFAULT">0</set>
diff --git a/wx b/wx
new file mode 120000
index 0000000..b00f3db
--- /dev/null
+++ b/wx
@@ -0,0 +1 @@
+include/wx
\ No newline at end of file
diff --git a/wxcode/bakefiles/presets/defaults.bkl b/wxcode/bakefiles/presets/defaults.bkl
index f653bad..37ab793 100644
--- a/wxcode/bakefiles/presets/defaults.bkl
+++ b/wxcode/bakefiles/presets/defaults.bkl
@@ -23,7 +23,7 @@
          you can set them once in these vars and wxcode-* templates will automatically
          use them. -->
     <set var="COMP_SRC" overwrite="0">$(fileList('src/*.c*'))</set>
-    <set var="COMP_HDR" overwrite="0">$(fileList('include/wx/*.h'))</set>
+    <set var="COMP_HDR" overwrite="0">$(fileList('wx/*.h'))</set>
 
 
     <!--    A simple variable used to understand if we are          -->
diff --git a/wxcode/bakefiles/presets/templates.bkl b/wxcode/bakefiles/presets/templates.bkl
index a18433f..d33cdf8 100644
--- a/wxcode/bakefiles/presets/templates.bkl
+++ b/wxcode/bakefiles/presets/templates.bkl
@@ -54,7 +54,7 @@
 
     <template id="wxcode-lib" template="wx-lib,wxlike,wxcode-basic">
         <install-to>$(LIBDIR)</install-to>
-        <install-headers-to>$(PREFIX)</install-headers-to>
+        <install-headers-to>$(INCLUDEDIR)</install-headers-to>
 
         <wxcode-dirname>$(SRCDIR)/lib</wxcode-dirname>
         <wxlike-libname prefix="wxcode">$(COMP_NAME)</wxlike-libname>
@@ -65,7 +65,7 @@
 
     <template id="wxcode-dll" template="wx,wxlike,wxcode-basic">
         <install-to>$(LIBDIR)</install-to>
-        <install-headers-to>$(PREFIX)</install-headers-to>
+        <install-headers-to>$(INCLUDEDIR)</install-headers-to>
 
         <wxlike-dirname>$(SRCDIR)/lib</wxlike-dirname>
         <wxlike-dllname prefix="wxcode">$(COMP_NAME)</wxlike-dllname>
-- 
2.8.1
```

**Comment by utelle** [comment] 2016-05-14 17:19
Well, yes, `bakefile` is a mess. The - very old - version 0.2.9 is used to generate the build files, mainly to support the `autoconf/automake` toolchain. The new `bakefile` version 1.x is still work in progress, uses a completely different syntax, is not adopted by `wxWidgets` itself, and does not yet support `autoconf/automake` - disqualifying it as an alternative. In fact, I moved away from `bakefile` to `premake` for my own projects. Unfortunately, `premake` doesn't support `autoconf/automake` either; that's why I kept `bakefile` up to now.

The file `wxsqlite3.pc.in`was added on request from the [Fedora project](https://fedoraproject.org/) several years ago. They are using this file for packaging `wxSQLite3` for Fedora, and except for the recent change request #2 I never got complaints that the file is not working as intended.

Since I develop mostly under Windows and support for symlinks in `git for Windows` is limited, I'm a bit reluctant to add symlinks to the repository. If there is a solution for your issue without requiring symlinks I would be fine to add any changes.

**Comment by hasufell** [comment] 2016-05-14 19:54
> The file wxsqlite3.pc.inwas added on request from the Fedora project several years ago. They are using this file for packaging wxSQLite3 for Fedora, and except for the recent change request #2 I never got complaints that the file is not working as intended.

Well, you can just sed the thing out, but the point is that an install directory `/usr/include/wx-3.0/wx/<header-files>` is currently not possible via just the build system. So you either move the files post-install or fix the `.pc` file post-install.

> If there is a solution for your issue without requiring symlinks I would be fine to add any changes.

Sure, you can just move `include/wx` to `wx`. It should build the same way.

**Comment by utelle** [comment] 2016-05-14 20:25
> Well, you can just sed the thing out, but the point is that an install directory `/usr/include/wx-3.0/wx/<header-files>` is currently not possible via just the build system. So you either move the files post-install or fix the `.pc` file post-install.

I don't know how the Fedora guys make use of this file. Personally, I would not recommend to merge the header files of `wxWidgets` itself and of independent wxWidgets based components like wxSQLite3. However, I'll probably talk to one of the wxWidgets developers, what is the recommended way to install wxWidgets based components.

> ... you can just move `include/wx` to `wx`. It should build the same way.

Sorry, I certainly will not do that. The name of the directory should make clear that the header files are to be found there.

**Comment by hasufell** [comment] 2016-05-14 20:43
> I don't know how the Fedora guys make use of this file.

That's not a distro-specific file. It's a file that is meant to be maintained by upstream (you) and standardizes the interface of how to interact with your package (similar to things like `wx-config`), which means people don't need to worry about distro-specific paths, because the file should properly be generated at build-time and must match the actual locations. People then interact with it via e.g. `pkg-config --libs wxsqlite3` and it is guaranteed to always do the right thing regardless of the distro. That's the idea at least. Also see https://www.freedesktop.org/wiki/Software/pkg-config/

> Sorry, I certainly will not do that. The name of the directory should make clear that the header files are to be found there.

Then I suggest you fix your build system (e.g. by using cmake which is cross-platform too) and integrate the generation of the `wxsqlite3.pc` file.

**Comment by scottfurry** [comment] 2016-05-14 21:22
I've been watching this thread from the sidelines...time to chime in<br/>

As previously stated, Ulrich is not from the Linux/Unix crowd. Not his fault and we shouldn't hold it against him. Rather than **barking** at the dev/maintainer that he is *doing it wrong*, one is more than welcome to chip in and give him a hand.

Fixing the ```pkg-config``` file is a work in progress. Fedora chooses to manipulate the generated file within the spec instructions. Arch doesn't do anything with the file. Yes, this is an issue. And yes, it can be fixed. Admonishment doesn't help.

**Comment by hasufell** [comment] 2016-05-14 21:31
> Rather than barking at the dev/maintainer that he is doing it wrong, one is more than welcome to chip in and give him a hand.

I don't see any barking. I've made 3 suggestions:
* apply my patch
* apply a modified version of my patch (by renaming the folder, which doesn't break anything)
* switch the build system

I cannot really come up with more solutions, sorry.

**Comment by scottfurry** [comment] 2016-05-14 21:37
This will not get resolved in timeline that satisfies you.
...again. Correctly generating the pkg-config file is a work in progress.
I will *review* your suggested patch/folder changes.

Thnak you for your contribution

**Comment by hasufell** [comment] 2016-05-14 22:55
> Correctly generating the pkg-config file is a work in progress.

The problem was rather that `--includedir=/some/thing` in the autotools-generated build system does nothing, basically making it hard to get the includedir right.

**Comment by utelle** [comment] 2016-05-14 23:24
> I've made 3 suggestions:
> - apply my patch

Your original patch requires to introduce symlinks. This makes things cumbersome on Windows - which is my main development platform ... and that of about 80% of the `wxSQLite3` users I'm aware of.

> - apply a modified version of my patch (by renaming the folder, which doesn't break anything)

True, it probably doesn't break anything, but it introduces an inconvenient renaming of a directory making things less intuitive. So I don't intend to follow your suggestion.

> - switch the build system

As mentioned I started to use `premake`. Some of the `wxSQLite3` build files were already generated with `premake`. 

> I cannot really come up with more solutions, sorry.

Oh, I'd see several:

- contribute `cmake` support to `wxSQLite3`
- contribute `autoconf/automake` support to `premake`
- lend a helping hand to improve things for `wxSQLite3`as [scottfurry](https://github.com/scottfurry) suggested

or - if all of the above is not to your liking -

- create a `wxSQLite3` fork and do whatever you like to make it fit for your needs

**Comment by hasufell** [comment] 2016-05-14 23:37
Seems like you want the most difficult solution. I'm afraid I don't have time for that so I will keep patching it downstream.

**Comment by scottfurry** [comment] 2016-05-14 23:39
Its not *wanting* a difficult solution, but rather meeting the needs of a diverse user base.
And meeting those needs without resorting to hacks and shims is best for long term maintainability.

**Comment by hasufell** [comment] 2016-05-15 00:42
> Its not wanting a difficult solution, but rather meeting the needs of a diverse user base.

I didn't say he wants the solution because it's difficult. It's the most clean solution, but it's also the most time-consuming one and needs a lot of cross-platform testing which I cannot do.

> And meeting those needs without resorting to hacks and shims is best for long term maintainability.

I don't consider renaming a directory short/mid-term a hack. It's rather a "hack" that `$(PREFIX)` is used instead of `$(INCLUDEDIR)` in https://github.com/utelle/wxsqlite3/blob/master/wxcode/bakefiles/presets/templates.bkl#L68 which is not autotools compatible.

**Comment by utelle** [comment] 2016-05-15 07:01
> Seems like you want the most difficult solution.

How do you come to that conclusion? My intention is - and always was - to make `wxSQLite3` usable on different platforms, namely Windows, Linux/Unix, and Mac OS X. Since I have limited experience with Linux/Unix and Mac OS X, achieving this goal needs support from experienced users of those platforms. 

> I'm afraid I don't have time for that so I will keep patching it downstream.

Now we are getting to the core of the matter: you want a solution that works for _you_, but you don't want to spend time on creating a clean solution that not only works for you, but also for others on other platforms - or at least doesn't break anything or makes it difficult to use on other platforms.

> It's the most clean solution, but it's also the most time-consuming one and needs a lot of cross-platform testing which I cannot do.

Unfortunately there doesn't seem to exist the one and only build system that works on all platforms out of the box. So, yes, a clean solution requires cross-platform testing. And, yes, this is time-consuming. Therefore the idea is to distribute the burden on many shoulders.

> I don't consider renaming a directory short/mid-term a hack. It's rather a "hack" that $(PREFIX) is used instead of $(INCLUDEDIR) ... which is not autotools compatible.

As I already said renaming directory `include/wx`to `wx` only, obscures the purpose of that directory. `wxWidgets` itself also didn't rename the `include` directory. So why should _I_ do that? This seems to inidcate that this might be a `bakefile` (or maybe only a `bakefile presets`) issue. If you can come up with a patch that just tweaks the `bakefile presets` files, I will happily consider to apply it.

**Closed** 2016-05-21 05:46 UTC

**Comment by hasufell** [comment] 2016-05-21 13:13
I don't see how this issue is solved. Why do you close it?
